### ISSUE TITLE
ZABAPGIT_CI stalls with WP Status: "On Hold", Info: "RFC Response" in background mode

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/CI#35]
I've started the CI process using ZABAPGIT_CI_JOB_SCHEDULER. But ZABAPGIT_CI doesn't finish. In SM50 I see WP Status: "On Hold", Info: "RFC Response":

![screen shot 2018-11-21 at 07 57 14](https://user-images.githubusercontent.com/2639535/48824003-36b24c80-ed63-11e8-9939-50af02b86c65.png)

Running the ZABAPGIT_CI in foreground doesn't bring up any dialog boxes and returned this result:

![screen shot 2018-11-21 at 08 23 41](https://user-images.githubusercontent.com/2639535/48825181-ea690b80-ed66-11e8-99b5-1a6342d831ed.png)

**Comment by gregorwolf** [comment]
No runtime errors.

**Comment by gregorwolf** [comment]
The debugger doesn't come up for the On Hold process. But I see this in the details of the process:

![screen shot 2018-11-21 at 18 04 55](https://user-images.githubusercontent.com/2639535/48857588-87549480-edb9-11e8-8c61-253818836bfa.png)

Seems there is an issue with HTTP requests that do not respond. But strange that it doesn't happen in foreground.

**Comment by gregorwolf** [comment]
Seems others also faced this issue: [System user, wait inline for HTTP input](https://answers.sap.com/questions/454802/runtime-information-system-user-wait-inline-for-ht.html)

**Comment by christianguenter2** [comment]
Background works for me.

**Comment by flaiker** [comment]
I ran into the same issue.

![image](https://user-images.githubusercontent.com/5270359/62835041-0c3b5300-bc54-11e9-8366-f9d6b7cb5f32.png)

![image](https://user-images.githubusercontent.com/5270359/62835045-152c2480-bc54-11e9-95f7-c0e6fc6f981d.png)

![image](https://user-images.githubusercontent.com/5270359/62835050-1f4e2300-bc54-11e9-8ca2-1f7b485b1771.png)

**Comment by flaiker** [comment]
For me the debugger did open after a few minutes.

![image](https://user-images.githubusercontent.com/5270359/62835179-61c42f80-bc55-11e9-8987-4497bcb8a860.png)

subrc = 2, system_failure

Seems like the cause is in zcl_abapgit_ci_repo->syntax_check( ), at least when I F6-ed over it for the next repo it got stuck again with the same status in SM50. The syntax check apparently has special handling for batch work processes which may cause the issue?
![image](https://user-images.githubusercontent.com/5270359/62835236-1fe7b900-bc56-11e9-858a-9f264c8a81ea.png)

In the default AS ABAP Dev edition configuration there are only two BTC processes available. Do RFC-Calls _inherit_ the process type of its parent? If so then running in batch would lead to no available processes for the syntax check as one is occupied by the main program and the other one by the check for the current repo. That would also explain why @christianguenter2 did not run into the issue as iirc you have tuned the number of processes available by quite a bit :)

**Comment by flaiker** [comment]
I thought maybe `co_run_mode-run_direct` would fix it but that is note the case.

**Comment by flaiker** [comment]
![image](https://user-images.githubusercontent.com/5270359/62835587-8ff83e00-bc5a-11e9-939f-04883ba56942.png)

**Comment by mbtools** [comment]
FYI, I ran the complete CI tests (382 test cases) on ABAP 7.54 docker image now over a dozen times. Dialog and background. It runs for about an hour. Never had this issue.

Suggest trying it with the latest version of the repo or just go to https://ci.abapgit.org/ 😃

**Comment by flaiker** [comment]
Great! Would be nice to have the SAP_BASIS version and support package level in the header as well for comparisons.

**Comment by mbtools** [comment]
It's working well for me. If this is still an issue, please re-open
